name: Publish Github Pages
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: Write-Host "Starting...!";

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.11'
          check-latest: true

      - name: Install Angular
        run: npm install -g @angular/cli@15.1;

      - name: info
        run: |
          Write-Host "Node Version:" -NoNewLine;
          node --version;
          ng version;
          pwd;
          tree;

      - name: npm install
        run: npm install

      - name: ng build
        run: ng build

      - uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: 'server-dekstop.jpg'

